from .company_route import router as company_router
from .corporate_route import router as corporate_router
from .department_route import router as department_router
from .service_route import router as service_router
from .profession_route import router as profession_router
from .position_route import router as position_router
from .employee_route import router as employee_router
from .user_account_route import router as user_account_router
from .system_role_route import router as system_role_router
from .material_route import router as material_router